esphome:
  name: biggaragedoor
  friendly_name: BigGarageDoor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret biggaragedoor-api_encryption_key

ota:
  - platform: esphome
    password: !secret biggaragedoor-ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Biggaragedoor Fallback Hotspot"
    password: !secret biggaragedoor-ap_password

captive_portal:
binary_sensor:
  - platform: gpio
    name: "Big Garage Door"
    id: dooropen
    on_state:
        if:
          condition:
            binary_sensor.is_on: dooropen
          then:
            - light.turn_on:
                id: open_indicator
                brightness: 50%
          else:
            - light.turn_off: open_indicator
    device_class: door
    pin:
      number: 14
      # inverted: true
      mode: INPUT_PULLUP

output:
  - platform: esp8266_pwm
    id: openindicator_led
    pin: GPIO2
    inverted: true
light:
  - platform: monochromatic
    output: openindicator_led
    name: "Open Indicator"
    id: open_indicator