substitutions:
  name: "hall-light"
  friendly_name: "Hall Light"
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
