substitutions:
  name: kauf-bulb-302c2c
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret kauf-bulb-302c2c-api_encryption_key
logger:
  baud_rate: 0
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
