substitutions:
  name: kauf-rgbsw-5115bf
  hass_light_entity: light.living_room_lamp
packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs-4m.yaml
  rotate_colors: github://KaufHA/kauf-rgb-switch/yaml-features/rotate-colors-sync-to-ha-light.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret kauf-rgbsw-5115bf-api_encryption_key
logger:
  baud_rate: 0
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
