substitutions:
  name: "living-room-lamp2"
  friendly_name: "Living Room Lamp"
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret living-room-lamp2-api_encryption_key

logger:
  baud_rate: 0
  level: INFO
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
