esphome:
  name: "livingroom"
  friendly_name: "Living Room"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # level: INFO
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret livingroom-api_encryption_key

ota:
  password: !secret livingroom-ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Remotetest Fallback Hotspot"
    password: !secret livingroom-ap_password
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 256000
  parity: NONE
  stop_bits: 1


ld2410:
captive_portal:
remote_transmitter:
  pin: GPIO14
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
remote_receiver:
  pin: 
    number: GPIO23
    inverted: true
    mode:
      input: true
      pullup: true
  dump: raw
  
    
switch:
  - platform: template
    id: stayon
    name: "Stay On"
    optimistic: true
  - platform: template
    id: stayoff
    name: "Stay Off"
    optimistic: true
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
  - platform: template
    name: "Soundbar Volume -"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
  - platform: template
    name: "Soundbar Volume +"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41
  - platform: template
    name: "Soundbar Mute"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB748
  - platform: template
    name: "Soundbar Input"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
  - platform: template
    name: "Soundbar Night"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6798
  - platform: template
    name: "Soundbar EQ Movie"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9867
  - platform: template
    name: "Soundbar EQ Music"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9966
  - platform: template
    name: "Soundbar EQ Dialog"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x21DE
  - platform: template
    name: "Living Room TV Toggle Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF708
  - platform: template
    name: "Flying Saucer"
    turn_on_action:
      remote_transmitter.transmit_canalsatld:
        device: 0x2A
        address: 0x2A
        command: 0x55
  - platform: template
    name: "Flying Saucer 2"
    turn_on_action:
      remote_transmitter.transmit_pronto:
        data: "0000 006D 0035 0000 000B 0018 0012 0019 0012 0018 0017 0015 0012 0019 0012 0018 0017 0015 0012 0019 0012 0018 0017 0015 0012 0019 0012 0018 0017 0015 0012 0019 0012 0018 0017 0015 0012 0019 0012 0018 0040 0017 003F 0016 003F 0016 0040 0017 0012 0018 0016 0015 0012 0019 0012 0018 0016 0016 0012 0019 0012 0018 0016 0016 0012 0019 0012 0018 003F 0017 003F 0016 003F 0016 003F 0017 0012 0018 0015 0016 0012 0019 0012 0018 0015 0016 0012 0019 0012 0018 0014 0017 0012 0019 0013 0018 003E 0017 003F 0016 003F 0016 003F 0017 0014 0016 0015 0016 0015 0181 06C3"
  - platform: template
    name: "Flying Saucer 3"
    turn_on_action:
      remote_transmitter.transmit_raw:
        code: [407, -588, 487, -642, 486, -616, 515, -613, 483, -645, 482, -619, 508, -619, 488, -641, 509, -591, 538, -591, 511, -619, 511, -590, 539, -591, 514, -619, 511, -590, 540, -589, 514, -619, 509, -564, 1668, -620, 1637, -591, 1614, -617, 1613, -642, 484, -495, 633, -617, 484, -643, 484, -619, 509, -617, 484, -645, 483, -619, 509, -619, 482, -646, 482, -618, 1608, -646, 1602, -620, 1603, -619, 1600, -647, 477, -622, 503, -621, 477, -648, 477, -621, 504, -621, 478, -624, 500, -621, 503, -621, 477, -648, 478, -621, 1597, -647, 1597, -621, 1777, -430, 1605, -647, 476, -621, 503, -620, 476, -648, 476, -621, 502, -622, 476, -648, 476, -621, 502, -621, 476, -649, 475, -622, 1596, -647, 1594, -621, 1596, -620, 1595, -647, 475, -622, 501, -622, 476, -648, 475, -622, 502, -601, 495, -628, 496, -601, 522, -601, 497, -627, 497, -601, 1615, -627, 1615, -601, 1614, -601, 1614, -627, 496, -602, 521, -601, 496, -627, 496, -601, 522, -602, 495, -648, 476, -601, 521, -602, 496, -647, 476, -622, 1594, -648, 1593, -621, 1594, -621, 1593, -647, 477, -620, 502, -620, 475, -648, 476, -621, 502, -621, 476, -647, 476, -621, 502, -620, 476, -648, 475, -622, 1594, -648, 1593, -621, 1593, -622, 1592, -647, 474, -623, 500, -622, 474, -649, 474, -622, 500, -623, 473, -649, 475, -623, 499, -624, 473, -649, 474, -624, 1593, -649, 1594, -623, 1593, -624, 1592, -651, 475, -624, 501, -623, 476, -650, 477, -624, 503, -624, 477, -651, 478, -623, 504, -624, 478, -650, 478, -625, 1604, -652, 1603, -626, 1607, -625, 1617, -652, 478]
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
status_led:
  pin:
    number: GPIO2 #ESP8266 OnBroad LED

    

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"