esphome:
  name: mailbox
  friendly_name: mailbox

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret mailbox-api_encryption_key

ota:
  - platform: esphome
    password: !secret mailbox-ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.86.53
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mailbox Fallback Hotspot"
    password: !secret mailbox-ap_password

captive_portal:
binary_sensor:
  - platform: gpio
    name: "Mail Box"
    device_class: door
    pin:
      number: 14
      # inverted: true
      mode: INPUT_PULLUP
sensor:
  - platform: adc
    name: Battery
    id: battery
    pin: A0
    update_interval: 1min
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:battery-medium
    on_raw_value:
      then:
         logger.log:
            format: "BERT The battery sensor reports value %.3f"
            args: [ 'id(battery).state' ]
    filters:
      - multiply: 4.56
      - calibrate_linear:
         method: exact
         datapoints:
          - 0.00 -> 0.0
          - 3.30 -> 1.0
          - 3.39 -> 10.0
          - 3.75 -> 50.0
          - 4.11 -> 90.0
          - 4.20 -> 100.0
      - lambda: |-
          if (x <= 100) {
            if (x <0) {
              return 0;
            } else {
              return x;
            }
          } else {
            return 100;
          }
          

deep_sleep:
  id: deep_sleep_1
  run_duration: 3min
