esphome:
  name: master-bedroom-ir-remote
  friendly_name: Master Bedroom IR Remote

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret master-bedroom-ir-remote-api_encryption_key

ota:
  - platform: esphome
    password: !secret master-bedroom-ir-remote-ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master-Bedroom-Ir-Remote"
    password: !secret master-bedroom-ir-remote-ap_password
# status_led:
#   pin:
#     number: GPIO2 #ESP8266 OnBroad LED
#     inverted: true
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
output:
  - platform: ledc
    id: motion_led
    pin: GPIO2
light:
  - platform: monochromatic
    output: motion_led
    name: "Motion Indicator"
    id: motion_indicator

ld2410:
captive_portal:
remote_transmitter:
  pin: GPIO13
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
switch:
  - platform: template
    id: stayon
    name: "Stay On"
    optimistic: true
  - platform: template
    id: stayoff
    name: "Stay Off"
    optimistic: true
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
  - platform: template
    name: "Bedroom TV Power"
    turn_on_action:
      remote_transmitter.transmit_lg:
        data: 0x20DF10EF # power on/off
        nbits: 32
  - platform: template
    name: "Bedroom TV Volume -"
    turn_on_action:
      remote_transmitter.transmit_lg:
        data: 0x20DFC03F
        nbits: 32
  - platform: template
    name: "Receiver Volume UP"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xE51A
  - platform: template
    name: "Receiver Volume DOWN"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xE41B
# # Volume UP
# [12:56:42][I][remote.jvc:049]: Received JVC: data=0x5EA1
# [12:56:42][I][remote.lg:054]: Received LG: data=0x5EA158A7, nbits=32
# [12:56:42][I][remote.nec:070]: Received NEC: address=0x857A, command=0xE51A
# [12:56:42][I][remote.pioneer:149]: Received Pioneer: rc_code_X=0x5E1A
# [12:56:42][I][remote.pronto:237]: Received Pronto: data=0000 006D 0022 0000 0157 00B3 0013 0019 0012 0044 0014 0019 0012 0044 0014 0043 0013 0045 0013 0043 0013 001A 0013 0043 0013 0019 0012 0044 0013 001A 0012 001A 0012 001A 0013 0018 0014 0044 0012 001A 0013 0043 0013 0019 0014 0043
# [12:56:42][I][remote.pronto:239]: 0014 0044 0012 001A 0012 001A 0013 0019 0013 0044 0013 0019 0012 0044 0014 0019 0013 0019 0012 0044 0014 0044 0012 0045 0012 0181 06C3

# Volume DOWN
# [12:57:50][I][remote.jvc:049]: Received JVC: data=0x5EA1
# [12:57:50][I][remote.lg:054]: Received LG: data=0x5EA1D827, nbits=32
# [12:57:50][I][remote.nec:070]: Received NEC: address=0x857A, command=0xE41B
# [12:57:50][I][remote.pioneer:149]: Received Pioneer: rc_code_X=0x5E1B
# [12:57:50][I][remote.pronto:237]: Received Pronto: data=0000 006D 0022 0000 0158 00B2 0013 0018 0014 0044 0012 001A 0012 0044 0014 0044 0013 0043 0014 0044 0012 0019 0014 0044 0013 0019 0013 0043 0013 001A 0013 0019 0013 0019 0013 0019 0013 0044 0013 0043 0014 0044 0012 001A 0013 0043
# [12:57:50][I][remote.pronto:239]: 0014 0043 0013 001A 0012 001A 0012 001A 0013 0019 0013 0018 0013 0045 0012 001A 0013 0019 0013 0044 0013 0044 0012 0045 0012 0181 06C3
# [12:57:50][W][component:214]: Component remote_receiver took a long time for an operation (0.06 s).
# [12:57:50][W][component:215]: Components should block for at most 20-30ms.
# [12:57:50][I][remote.pronto:237]: Received Pronto: data=0000 006D 0002 0000 0156 005B 0013 0181 06C3
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: presence
      on_state:
        if:
          condition:
            binary_sensor.is_on: presence
          then:
            - light.turn_on: 
                id: motion_indicator
                brightness: 25%
          else:
            - light.turn_off: motion_indicator
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
# [21:06:51][I][remote.jvc:049]: Received JVC: data=0x5EA1
# [21:06:51][I][remote.lg:054]: Received LG: data=0x5EA158A7, nbits=32
# [21:06:51][I][remote.nec:098]: Received NEC: address=0x857A, command=0xE51A command_repeats=1
# [21:06:51][I][remote.pioneer:149]: Received Pioneer: rc_code_X=0x5E1A
# [21:06:51][I][remote.pronto:234]: Received Pronto: data=
# [21:06:51][I][remote.pronto:236]: 0000 006D 0022 0000 0158 00B1 0014 0019 0013 0044 0013 0019 0013 0044 0013 0044 0013 0044 0013 0044 0013 0019 0013 0044 0013 0019 0013 0044 0013 0019 0013 0019 0013 0019 0013 0019 0013 0044 0013 0019 0013 0044 0013 0019 0013 0044 
# [21:06:51][I][remote.pronto:236]: 0013 0044 0013 0019 0013 0019 0013 0019 0013 0044 0013 0019 0013 0044 0013 0019 0013 0019 0013 0044 0013 0044 0013 0044 0013 0181 06C3
# [21:06:51][W][component:237]: Component remote_receiver took a long time for an operation (69 ms).
# [21:06:51][W][component:238]: Components should block for at most 30 ms.
# [21:06:51][I][remote.pronto:234]: Received Pronto: data=
# [21:06:51][I][remote.pronto:236]: 0000 006D 0002 0000 0157 0059 0014 0181 06C3
# [21:06:51][D][sensor:094]: 'Still Distance': Sending state 192.00000 cm with 0 decimals of accuracy
# [21:06:51][D][sensor:094]: 'Still Energy': Sending state 65.00000 % with 0 decimals of accuracy
# [21:06:51][D][sensor:094]: 'Detection Distance': Sending state 188.00000 cm with 0 decimals of accuracy
# [21:06:52][I][remote.jvc:049]: Received JVC: data=0x5EA1
# [21:06:52][I][remote.lg:054]: Received LG: data=0x5EA1D827, nbits=32
# [21:06:52][I][remote.nec:098]: Received NEC: address=0x857A, command=0xE41B command_repeats=1
# [21:06:52][I][remote.pioneer:149]: Received Pioneer: rc_code_X=0x5E1B
# [21:06:52][I][remote.pronto:234]: Received Pronto: data=
# [21:06:52][I][remote.pronto:236]: 0000 006D 0022 0000 0159 00B1 0014 0019 0013 0044 0013 0019 0013 0044 0013 0044 0013 0044 0013 0044 0013 0019 0013 0044 0013 0019 0013 0044 0013 0018 0013 0019 0014 0018 0014 0018 0013 0044 0013 0044 0013 0043 0013 0019 0014 0043 
# [21:06:52][I][remote.pronto:236]: 0014 0043 0013 0019 0014 0018 0013 0019 0013 0019 0014 0018 0014 0043 0014 0018 0014 0018 0013 0044 0013 0044 0014 0043 0014 0181 06C3
# [21:06:52][W][component:237]: Component remote_receiver took a long time for an operation (64 ms).
# [21:06:52][W][component:238]: Components should block for at most 30 ms.
# [21:06:52][I][remote.pronto:234]: Received Pronto: data=
# [21:06:52][I][remote.pronto:236]: 0000 006D 0002 0000 0158 0058 0013 0181 06C3